# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-26 10:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockExpert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('stock_player_revenue', models.FloatField()),
                ('stock_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockMarket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_evolution', models.FloatField()),
                ('stock_expert_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sm_user.StockExpert')),
            ],
        ),
    ]
