# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-26 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmarket',
            name='stock_evolution',
            field=models.FloatField(default=0),
        ),
    ]
