# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-26 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm_user', '0004_auto_20190626_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockexpert',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
