# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-26 13:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sm_user', '0005_stockexpert_email_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockexpert',
            name='stock_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_player', to=settings.AUTH_USER_MODEL),
        ),
    ]
