# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-26 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sm_user', '0007_auto_20190626_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockexpert',
            name='email_confirmed',
        ),
    ]
