# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-28 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm_user', '0009_auto_20190628_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmarket',
            name='stock_moment',
            field=models.CharField(default='--/--/--', max_length=30),
        ),
    ]
