# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-28 09:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sm_user', '0010_stockmarket_stock_moment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmarket',
            name='stock_expert_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
