# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-28 10:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm_user', '0011_auto_20190628_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmarket',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 28, 10, 20, 4, 498558)),
        ),
    ]
