# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-01 08:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm_user', '0015_auto_20190628_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmarket',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 1, 8, 36, 32, 92142)),
        ),
    ]
