# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-01 08:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm_user', '0016_auto_20190701_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmarket',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 1, 8, 38, 27, 496709)),
        ),
    ]
